version: '3.8'

services:
  inscriptum-api-cache-server: 
    image: redis/redis-stack:latest
    volumes:
      - ./data:/data
      - ./redis-stack.conf:/redis-stack.conf
    ports:
      - 6379:6379
      - 8001:8001
    restart: unless-stopped
    networks:
      - default




